[requirements]
packages = ["scons", "build-essential", "fakeroot", "libssl-dev", "zlib1g-dev", "libbz2-dev", "liblz4-dev", "libsystemd-dev"]
	
[[download.files]]
	url = "https://github.com/vi/websocat/releases/latest/download/websocat.x86_64-unknown-linux-musl"
	dest = "websocat"
	post = "chmod +x websocat"

	
[network]
	allowed_hosts = [
	    "foldingathome.org",
	    "v8-5.foldingathome.org",
	    "app.foldingathome.org",
	    "master.foldingathome.org",
	    "api.foldingathome.org",
	    "api2.foldingathome.org",
	    "api3.foldingathome.org",
	    "api4.foldingathome.org",
	    "api5.foldingathome.org",
	    "assign1.foldingathome.org",
	    "assign2.foldingathome.org",
	    "assign3.foldingathome.org",
	    "assign4.foldingathome.org",
	    "assign5.foldingathome.org",
	    "assign6.foldingathome.org",
	    "cores.foldingathome.org",
	    "cores2.foldingathome.org",
	    "node1.foldingathome.org",
	    "vav17.fah.temple.edu",
	    "vav18.fah.temple.edu",
	    "vav19.fah.temple.edu",
	    "vav20.fah.temple.edu",
	    "vav21.fah.temple.edu",
	    "vav22.fah.temple.edu",
	    "vav23.fah.temple.edu",
	    "vav24.fah.temple.edu",
	    "highland1.seas.upenn.edu",
	    "highland2.seas.upenn.edu",
	    "highland3.seas.upenn.edu",
	    "highland4.seas.upenn.edu",
	    "highland5.seas.upenn.edu",
	]

[outputs]
	dir = "work"

[hash]
    exclude = ["cbang", "fah-client-bastet"]
