[requirements]
packages = ["make", "wget", "adduser"]

[[download.files]]
	url = "https://download.foldingathome.org/releases/public/fah-client/debian-10-64bit/release/fah-client_8.5.5_amd64.deb"
	dest = "fah-client_8.5.5_amd64.deb"

